---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:


- project: cp4waiops-evtmgr
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Event Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-eventmanager
    kind: EventManager
    install: true
    # Version of the catalog subscription
    subscription_channel: v1.7




# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS GLOBAL CONFIGURATION
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC
storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC



# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Pull Registires
# --------------------------------------------------------------------------------------------------------------------------------------

# entitled_registry: cp.stg.icr.io
# entitled_registry_user: cp
# catalog_image: icr.io/cpopen/ibm-operator-catalog:latest

# from #katamari-bvt-notifications
entitled_registry: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com
entitled_registry_user: nikh@ch.ibm.com
#catalog_image: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.4.0-20220601.2001-4674c29a5
#catalog_image: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.4.0-20220608.0002-837400c20
catalog_image: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.4.0-20220613.1602-da192e105



#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
ocp_major_version: automatic
