

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.4.0
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - WAIOPS Operator
#  - AI Manager
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 


- name: INSTALLATION MODULE -           🚀 Install Module
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       🚀 CloudPak for Watson AIOps v3.4.0 - INSTALLING {{current_cp4waiops_feature.kind}} "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"



- name: Installing {{current_cp4waiops_feature.kind}} with the following configuration
  debug:
    var: current_cp4waiops_feature


- name: And the following global configuration
  debug:
    var: cp4waiops



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: 00_init-custom-hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: 01_init-logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"
    
- name: 02_init_checks
  include_tasks: 02_init_checks.yaml
# Start block
- name: 90-log-start
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"

# Run Prerequisites
- name: 03_init-initialization
  include_tasks: 03_init-initialization.yaml
  

- name: 05_init-get-storage-class
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/05_init-get-storage-class.yaml"
      
- name: 06_aimanager-prerequisites
  include_tasks: 06_aimanager-prerequisites.yaml
      



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL AI MANAGER
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install CP4WAIOPS Operator
- name: 10_aimanager-custom-hook
  include_tasks: 10_aimanager-custom-hook.yaml
- name: 11_aimanager-operator
  include_tasks: 11_aimanager-operator.yaml
      
      
# Install CP4WAIOPS Instance
- name: 12_aimanager-install
  include_tasks: 12_aimanager-install.yaml
      




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# WAIT FOR INSTALLATION READY
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Wait for Common Services being completely installed
- name: 99_aimanager-wait-common-services
  include_tasks: 99_aimanager-wait-common-services.yaml
- name: 99_aimanager-wait-for-zen
  include_tasks: 99_aimanager-wait-for-zen.yaml
      

# Patching Topology Deployment
- name: 20_aimanager-patch-topology
  include_tasks: 20_aimanager-patch-topology.yaml


# Wait for CP4WAIOPS being completely installed
- name: 99_aimanager-wait-cp4waiops
  include_tasks: 99_aimanager-wait-cp4waiops.yaml



# Access and documentaiton
- name: 90_core-get-all-logins
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90_core-get-all-logins.yaml"

- name: 99_open-aimanager
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-aimanager.yaml"


- name: 99_open-doc
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-doc.yaml"



- name: 91-log-end
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks//91-log-end.yaml"




- name: INSTALLATION MODULE -           🚀 Install Module
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ✅ CloudPak for Watson AIOps v3.4.0 - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
