

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.4.0
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - WAIOPS Operator
#  - Event MAnager
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: INSTALLATION MODULE -           🚀 Install Module
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       🚀 CloudPak for Watson AIOps v3.4.0 - INSTALLING {{current_cp4waiops_feature.kind}}                                                                                          "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: 00_init-custom-hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: 01_init-logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"

- name: 05_init-get-storage-class
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/05_init-get-storage-class.yaml"

  
# Start block
- name: 90-log-start
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL EVENT MANAGER
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: 01_eventmanager-install.yaml
  include_tasks: 01_eventmanager-install.yaml



# Access and documentaiton
- name: 90_core-get-all-logins
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90_core-get-all-logins.yaml"

- name: 99_open-eventmanager
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-eventmanager.yaml"

- name: 99_open-doc
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-doc.yaml"




- name: 91-log-end
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"



- name: INSTALLATION MODULE -           🚀 Install Module
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ✅ CloudPak for Watson AIOps v3.4.0 - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
