- name: 🛰️  START - RESET ANOMALY DETECTION
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"



- name: Log
  shell: |
    export MESSAGE="Reset Anomaly Detection Pods"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes



- name: 🚀 ANOMALY DETECTION - RESET ANOMALY DETECTION
  shell: |
    set -x
    

    oc delete pod $(oc get po -n {{current_cp4waiops_cluster.project}}|grep anomaly|awk '{print$1}') -n {{current_cp4waiops_cluster.project}}

  register: output_string
  ignore_errors: yes
