
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.4.0
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - OpenLDAP & Register with AI Manager
#  - RobotShop Demo App
#  - Demo Service Account 
#  - AWX (Open Source Ansible Tower) with preloaded Playbooks
#  - Disables ASM Service match rule 
#  - Train Models
#    - Create Training Definitions (TG, LAD, CR, SI. Turn off RSA) 
#    - Create Training Data (LAD, SNOW) 
#    - Train Models (TG, LAD, CR, SI) 
#  - Topology
#    - Create K8s Observer
#    - Create ASM merge rules
#    - Load ASM merge Topology
#    - Create AI Manager Application
#  - Creates valid certificate for Ingress (Slack) 
#  - External Routes (Flink, Topology, ...)
#  - Disables ASM Service match rule 
#  - Create Policy Creation for Stories and Runbooks 

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- name: INSTALLATION MODULE -           🚀 Install Module
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       🚀 CloudPak for Watson AIOps v3.4.0 - INSTALLING {{current_cp4waiops_feature.kind}}                                                                                          "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Initialize Logging
- name: 01_init-logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"
    


- name: INITIALIZATION -         📥  Installation Parameters"
  debug:
    msg:
    - "** Installation Options ***********************************************************************"
    - " Storage Class File Override:      {{config_file.storage_class_file}}"
    - " Storage Class Block Override:     {{config_file.storage_class_block}}"
    - " Storage Class InfraManagement:    {{config_file.storage_class_file}}"
    - ""
    - "** Additional Content *************************************************************************"
    - "  LDAP Domain:                     {{current_cp4waiops_feature.ldap_domain}}"
    - "  LDAP Base:                       {{current_cp4waiops_feature.ldap_base}}"
    - "  LDAP Admin Password:             {{current_cp4waiops_feature.ldap_admin_password}}"





# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Create Policies
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Create Story Creation and Runbook Policies
- name: 50_aimanager-create-policies-stories.yaml
  include_tasks: 50_aimanager-create-policies-stories.yaml
- name: 50_aimanager-create-policies-runbooks-file.yaml
  include_tasks: 50_aimanager-create-policies-runbooks-file.yaml
- name: 50_aimanager-create-policies-runbooks.yaml
  include_tasks: 50_aimanager-create-policies-runbooks.yaml




# Access and documentaiton
- name: 90_core-get-all-logins
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90_core-get-all-logins.yaml"



- name: 99_open-aimanager
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-aimanager.yaml"

- name: 99_open-demoui
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-demoui.yaml"


- name: 99_open-doc
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-doc.yaml"



- name: 91-log-end
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"





- name: INSTALLATION MODULE -           🚀 Install Module
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ✅ CloudPak for Watson AIOps v3.4.0 - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
