# number of pods to be expected in final cp4waiops namespace
waiops_ns_min_pods_final: 124
# number of pods to be expected in final ai manager namespace
cs_ns_min_pods: 34
# Link to documentation
url_doc: https://github.ibm.com/NIKH/aiops-install-ansible-33#3-ai-manager-configuration